# Generated by Django 5.0.7 on 2024-07-16 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-published_date']},
        ),
    ]
