# Generated by Django 5.0.7 on 2024-07-25 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='poster',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
